package com.gdg.Todak.point;

public enum PointType {
    ATTENDANCE_DAY_1,
    ATTENDANCE_DAY_2,
    ATTENDANCE_DAY_3,
    ATTENDANCE_DAY_4,
    ATTENDANCE_DAY_5_OR_MORE,
    DIARY,
    COMMENT,
    GROWTH_WATER,
    GROWTH_SUN,
    GROWTH_NUTRIENT,
    GET_COMMENT_WRITER_ID
}
